
---
source:
  server: tcp://127.0.0.01:12345
  envelopes:
    arrivals: "/RIG/InfoPlusDASInterface4"
    departures: "/RIG/InfoPlusDVSInterface4"
    services: "/RIG/InfoPlusRITInterface2"
redis:
  address: :6379
  password: ""
  db: 0
