---
ndov:
  server: tcp://127.0.0.1:12345
  sources:
    dvs: /RIG/InfoPlusDASInterface4
    das: /RIG/InfoPlusDVSInterface4
    rit: /RIG/InfoPlusRITInterface2
    pil: /RIG/InfoPlusPILInterface5
    vtbl: /RIG/InfoPlusVTBLInterface5
    lab-v2: /RIG/InfoPlusPILInterface6
    treinpos: /RIG/NStreinpositiesInterface5
outputs:
  redis:
    type: redis
    url: redis://127.0.0.1:6379/0
